services:
  smartlogisticsbackend:
    image: smartlogisticsbackend
    build:
      context: .
      dockerfile: ./SmartLogisticsBackend/Dockerfile.dev
    command: "bash init.sh"
    ports:
      - "5001:5001"
    volumes:
      - .:/src
    working_dir: /src/SmartLogisticsBackend
    environment:
      DOTNET_WATCH_RESTART_ON_RUDE_EDIT: true
      DOTNET_USE_POLLING_FILE_WATCHER: 1
      ASPNETCORE_ENVIRONMENT: Development
  
  SmartLogisticsDB:
    image: postgres:17-alpine
    container_name: database-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart_logistics_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: